### ISSUE TITLE
[suggestion] Afficher dates DD/MM/YYYY

### ISSUE THREAD

**Issue by Shohreh** [jesuisundesdeux/vigilo-webapp#16]
Bonjour,

Actuellement, l'appli web affiche les dates au format MM/DD/YYYY plutôt que DD/MM/YYYY.

Si c'est dû à l'appli plutôt qu'à mon OS+navigateur, je suggère de modifier le format de date.

My .15€
![image](https://user-images.githubusercontent.com/1541861/58461962-283d5700-8131-11e9-9297-46328d64d37c.png)

**Comment by tcoupin** [comment]
Bonjour @Shohreh,

le format de la date dépend du réglage du navigateur. Chez moi c'est bien le format DD/MM/YYYY
![image](https://user-images.githubusercontent.com/7457386/58462139-8d914800-8131-11e9-9e05-926b4ffa1e19.png)
