### ISSUE TITLE
[suggestion] Pouvoir filtrer par ville

### ISSUE THREAD

**Issue by Shohreh** [jesuisundesdeux/vigilo-webapp#19]
Pour que la police puisse facilement voir les problèmes qui concernent une ville donnée, il serait pratique sur la carte d'ajouter une combo pour limiter l'affichage à telle ou telle ville.

**Comment by Shohreh** [comment]
Je confirme l'importance de pouvoir au minimum filtrer pour ne voir que les items qui concernent une ville donnée… mais, pour que des villes non-encore équipées d'une solution adoptent Vigilo, il faut également trouver un moyen de le connecter à leur système de gestion des problèmes de voirie.

Ce point a été mentionné récemment par Rodéric Aarsse, maire adjoint de Malakoff délégué au développement durable et l’aménagement numérique.

**Comment by Shohreh** [comment]
C''est dommage de ne toujours pas pouvoir **filter par ville** : la police municipale pourrait ainsi facilement repérer les problèmes qui la concerne.

![image](https://user-images.githubusercontent.com/1541861/64081430-10153f00-cd01-11e9-8802-7d9f894c367a.png)

**Comment by tcoupin** [comment]
Fait sur la version 1.6.0
![image](https://user-images.githubusercontent.com/7457386/69500989-bcca1b80-0f00-11ea-9d0a-a821f6ad2892.png)

**Comment by tcoupin** [comment]
Note : Ne fonctionne que pour les zones géo ayant leur serveur en version > 0.0.13
