### ISSUE TITLE
Metadata (date/heure) pas extraires de la photo

### ISSUE THREAD

**Issue by DenisFeurer** [jesuisundesdeux/vigilo-webapp#23]
## Bug

Metadata (date/heure) pas extraites de la photo

N.B : Je ne sais pas si c'est un bug ou si simplement la fonctionnalité n'est pas encore développée...

## Navigateur

Firefox 67.0.1 sur Ubuntu 18.10

## Version

1.2.1

---- Bonjour et grand énormissime merci aux développeurs !!

**Comment by tcoupin** [comment]
C'est censé fonctionner pourtant...
Je pourrais avoir la photo originale ? En dm sur le slack.

**Comment by tcoupin** [comment]
Quand j'avais implémenté, il y avait 2 endroits où trouver la date et l'heure... Dans ta photo, ce n'est qu'à un seul endroit ;)
La correction est faite, elle sera déployée plus tard dans la journée (v1.3.0)
