### ISSUE TITLE
Absence support PNG

### ISSUE THREAD

**Issue by Shohreh** [jesuisundesdeux/vigilo-webapp#24]
L'appli ne gère que les JPG. Erreur incompréhensible (faut chercher) quand on essaye d'envoyer un PNG.

**Comment by tcoupin** [comment]
Le backend ne supporte que le jpeg. 
Ping @kentiss34 pour plus d'info.
Mais perso je ne connais pas beaucoup d'appareil photo qui sorte du png.

**Comment by kentiss34** [comment]
Effectivement le backend supporte uniquement du jpeg, car format photo standard avec EXIF et léger.
Pour les erreurs affichées, c'est dans la roadmap.

**Comment by DenisFeurer** [comment]
Pour info je rencontre le même type de problème car je fais des captures d'écran de mes vidéos et les captures d'écran sortent du PNG.

En passant quel bonheur l'app web !!!!

**Comment by tcoupin** [comment]
En fait, j'aurais du réfléchir... c'était facile dans la webapp de supporter le png.
La 1.4.1 supporte donc tous les format classiques (jpeg, png, gif...)

**Comment by DenisFeurer** [comment]
wahou super ! Merci beaucoup Thibault !!

    Le jeudi 20 juin 2019 à 21:04:27 UTC+2, Thibault Coupin <notifications@github.com> a écrit :  
 
 
En fait, j'aurais du réfléchir... c'était facile dans la webapp de supporter le png.
La 1.4.1 supporte donc tous les format classiques (jpeg, png, gif...)
