### ISSUE TITLE
Problème d'entête CORS lors de la soumission

### ISSUE THREAD

**Issue by bagage** [jesuisundesdeux/vigilo-webapp#25]
## Bug

Lorsqu'on essaye de soumettre un signalement via https://app.vigilo.city/#!, on a une erreur :

![image](https://user-images.githubusercontent.com/1451988/59303480-97b95780-8c96-11e9-904d-a5b2d30c5f92.png)

![image](https://user-images.githubusercontent.com/1451988/59303493-9daf3880-8c96-11e9-9bce-1ddf6247f927.png)

> Blocage d’une requête multiorigines (Cross-Origin Request) : la politique « Same Origin » ne permet pas de consulter la ressource distante située sur https://api-vigilo.jesuisundesdeux.org/add_image.php?token=LVWKKTAO&secretid=5d000b9c13c92142108877. Raison : échec de la requête CORS.

## Navigateur

Firefox 67.0.1 sous debian.

## Version

1.3.0

**Comment by tcoupin** [comment]
Bonjour @bagage,
je ne reproduit pas le bug. Est-ce qu'un nouvel essai a été fait depuis ?

**Comment by bagage** [comment]
Le problème est toujours d'actualité (sur firefox).

Pour info ce qui échoue est l'appel à `add_image.php`, parce qu'il manque vraisemblablement l'entête CORS :

```

**Comment by bagage** [comment]
Par contre ça marche comme attendu sous Chromium.

**Comment by tcoupin** [comment]
Bon je viens de tenté à nouveau...
La requête curl m'a bien renvoyée les entête cors attendus, quans je fais une requête OPTIONS aussi.
D'ailleurs au passage, comme j'ai fait le curl avec un image vide donc le signalement est affiché sur les appli mais avec une photo noire. Veux-tu qu'on la supprime peut-être ?

J'ai testé sur firefox 67.0.1 sur ubuntu mais ça marche (cf mes captures d'écran).

Peux-tu retesté est enregistrer les requêtes réseau et me faire parvenir ? dans la console, onglet réseau, c'est le bouton en haut à droite "HAR"

![image](https://user-images.githubusercontent.com/7457386/59499313-72e00280-8e97-11e9-959b-735fd75605f1.png)
![image](https://user-images.githubusercontent.com/7457386/59499392-9c992980-8e97-11e9-9418-5ad5b9118027.png)

**Comment by bagage** [comment]
J'ai retesté aujourd'hui et ça a fonctionné ! 

Je clos le ticket du coup, merci @tcoupin :) !
