### ISSUE TITLE
Bug récent : "Undefined index"

### ISSUE THREAD

**Issue by Shohreh** [jesuisundesdeux/vigilo-webapp#27]
Google Chrome.

Première fois que je vois ce bug, dernière création il y a deux jours environ.

![image](https://user-images.githubusercontent.com/1541861/61482043-ff4f7a80-a999-11e9-9d8a-2dd09059c253.png)

**Comment by tcoupin** [comment]
Est-ce que je peux avoir la photo ?

**Comment by Shohreh** [comment]
https://postimg.cc/8FWWBfng

Ça recommence, avec d'autres photos. Donc a priori, pas un pb de photo.

Création problème > Soumettre :

Oups... une erreur est survenue. HTTP Code: 200 (OK)
Notice: Undefined index: postcode in /var/www/html/create_issue.php on line 149
{"token":"62F1642E","status":0,"secretid":"5d3207e690dfc115168060","group":0}

Chrome. Même punition avec Firefox.

**Comment by Shohreh** [comment]
Même bug avec une autre machine.

HTTP Code: 200 (OK) 
Notice: Undefined index: postcode in /var/www/html/create_issue.php on line 149
{"token":"2F80642A","status":0,"secretid":"5d41d88f8cd11643255928","group":0}

Faut-il vider les cookies ?

**Comment by tcoupin** [comment]
J'aurais du m'en rendre compte plus tôt : problème de géocodage côté serveur.

**Comment by tcoupin** [comment]
Arf, je ne peux pas transférer cette issue directement. @kentiss34 tu peux regarder ça ?

**Comment by kentiss34** [comment]
Fixé dans https://github.com/jesuisundesdeux/vigilo-backend/commit/0d9ca743b908646a03456884fffbd7beaddd2a2a
