### ISSUE TITLE
Formulaire responsive

### ISSUE THREAD

**Issue by bagage** [jesuisundesdeux/vigilo-webapp#28]
Le formulaire d'ajout d'un signalement n'est pas idéal sur mobile, beaucoup de place en largeur est perdu :

![image](https://user-images.githubusercontent.com/1451988/65276974-36244700-db29-11e9-8874-212d3b4b26f9.png)

Je pense qu'il ne faudrait pas utiliser des `card` pour le formulaire, selon [la documentation](https://materializecss.com/cards.html) c'est fait pour grouper des objets similaires : 

> Cards are a convenient means of displaying content composed of different types of objects. They’re also well-suited for presenting similar objects whose size or supported actions can vary considerably, like photos with captions of variable length.

Ce n'est donc pas très adapté pour un formulaire à mon avis. Des simples séparateurs pour les différents morceaux du formulaire sont peut-être plus adaptés ici.

PS : je n'utilise pas l'appli Android car elle nécessite google maps que je n'ai pas, mais la webapp fait bien le taf ;).

**Comment by tcoupin** [comment]
J'ai enlevé quelques marges.
On passe de ça :
![image](https://user-images.githubusercontent.com/7457386/69919306-c4973c00-147b-11ea-8e56-c9915045700f.png)

a ça :
![image](https://user-images.githubusercontent.com/7457386/69919309-cb25b380-147b-11ea-868f-be71518e4c6a.png)

**Comment by bagage** [comment]
Super, merci @tcoupin ! L'input pour la photo reste un poil trop grand en hauteur pour une raison que j'ignore, mais c'est déjà nettement mieux :).

**Comment by tcoupin** [comment]
et là ? (au passage j'ai centré ce bouton qui commencé à m'énerver...)
![image](https://user-images.githubusercontent.com/7457386/69919759-b1d33600-1480-11ea-8a6b-d56b4f6dd490.png)

**Comment by bagage** [comment]
Ah ben parfait comme ça ! On pourra quasi sélectionner la catégorie sans devoir scroller :).

**Comment by tcoupin** [comment]
Content que ça te fasse plaisir !
Déploiement en cours v1.7.1..
