### ISSUE TITLE
Chargement infini sur Safari en 4G

### ISSUE THREAD

**Issue by cederache** [jesuisundesdeux/vigilo-webapp#31]
## Bug

Chargement infini lors de l’utilisation en 4g (fonctionnement correct si wifi)

## Navigateur

Sur Safari sous iOS 13.1.1

## Version

Version 1.5.0

**Comment by tcoupin** [comment]
Est ce que c'est le cas pour toute les zones géographiques ??

**Comment by cederache** [comment]
Je n'ai pas testé avec d'autre zones géographiques. Le chargement semble être revenu depuis la 4G
