### ISSUE TITLE
Problème suite à ajout catégorie

### ISSUE THREAD

**Issue by kentiss34** [jesuisundesdeux/vigilo-webapp#38]
## Bug

Message d'erreur à l'ouverture 

## Navigateur

Tous

## Version

Version en prod 

Voir tweet : https://twitter.com/demorose/status/1196355620418572289

**Comment by tcoupin** [comment]
Quelle est cette nouvelle catégorie ? elle a été ajouté uniquement sur l'instance de Nantes ?

**Comment by kentiss34** [comment]
Elle a été ajoutée sur Firebase donc sur l'ensemble des instances.

https://vigilo-bf7f2.firebaseio.com/categorieslist.json

**Comment by kentiss34** [comment]
Voir PR #41
