### ISSUE TITLE
Filtre non actif

### ISSUE THREAD

**Issue by franck-paul** [jesuisundesdeux/vigilo-webapp#44]
## Bug

Appli web (MacOS ou iOS), le résultat est le même, dès que je désactive l'affichage des signalements « Résolus », la liste (ou la carte) est vide.

Alors soit les services municipaux ou autres sont super réactifs sur la partie Vallée Sud Grand Paris, soit c'est un vrai bug (je penche pour le second) :-)

## Navigateur

Chrome MacOS, iOS

## Version

1.5.2

**Comment by franck-paul** [comment]
Bon c'est moi qui n'avait pas compris qu'il fallait recharger la page pour obtenir l'affichage filtré correctement.

Il serait opportun de le signaler quelque part dans la popup des filtres, je pense.

**Comment by tcoupin** [comment]
Lorsqu'on modifie les filtres, ils ne sont pas appliqués en direct, il faut refermer le panneau filtre.

**Comment by tcoupin** [comment]
Je vais ajouter un bouton "appliquer" pour que ce soit plus explicite

**Comment by franck-paul** [comment]
> Lorsqu'on modifie les filtres, ils ne sont pas appliqués en direct, il faut refermer le panneau filtre.

Ah non, aucune modification pour moi que ce soit côté liste ou carte (vais jeter un œil à la console…)

**Comment by franck-paul** [comment]
> > Lorsqu'on modifie les filtres, ils ne sont pas appliqués en direct, il faut refermer le panneau filtre.
> 
> Ah non, aucune modification pour moi que ce soit côté liste ou carte (vais jeter un œil à la console…)

Je retire ce que j'ai dit, en effet il y a bien requête (je suppose) et application sur la carte/liste. C'est juste qu'il n'y a quasi aucune différence entre "sans filtre" et "tout sauf résolu" du côté VSGP :-p

Je pense que je peux fermer ce ticket, merci !
