### ISSUE TITLE
bug appli vigilo android

### ISSUE THREAD

**Issue by 7castor** [jesuisundesdeux/vigilo-webapp#47]
## Bug

Indiquez ici le comportement anormal

## Navigateur

Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:71.0) Gecko/20100101 Firefox/71.0

## Zone géographique

Nantes Métropole

## Version

- Webapp : 1.7.1
- Serveur : 0.0.12
- portable huawei p8 2017
- version android 8.0.0
bonjour,
lorsque je veux signaler un problème l'appli bugue lors du chargement de la photo (prise à partir de l'appli ou stockée).
Les photos sont stockées sur une sdcarte.
cordialement.
JB TRIQUET

**Comment by tcoupin** [comment]
Il s'agit bien d'un bug de l'appli Android et non de la webapp app.vigilo.city ?

**Comment by 7castor** [comment]
Oui. Je suis passé par la webapp car je n’ai pas trouvé sur l’appli android comment signaler un bug.

 

De : Thibault Coupin [mailto:notifications@github.com] 
Envoyé : lundi 9 décembre 2019 15:35
À : jesuisundesdeux/vigilo-webapp
Cc : 7castor; Author
Objet : Re: [jesuisundesdeux/vigilo-webapp] bug appli vigilo android (#47)

 

Il s'agit bien d'un bug de l'appli Android et non de la webapp app.vigilo.city ?

**Comment by tcoupin** [comment]
ping @kentiss34 c'est pour toi !

**Comment by kentiss34** [comment]
Bonjour,

Quelle est la version de l'application sur Android ?
L'application est elle installée sur la carte SD ?
Quel est le bug en question, (message d'erreur ? si oui lequel ?)

Cordialement

**Comment by 7castor** [comment]
Bonjour,

 

Quelle est la version de l'application sur Android ? 8.0.0

L'application est elle installée sur la carte SD ? Non

Quel est le bug en question, (message d'erreur ? si oui lequel ?) oui  message erreur : erreur de copie du fichier dans file//mnt…. Le message est furtif 2 à 3 secondes.

Les photos sont stockéees sur la carte SD

Cordialement.

 

 

De : kentiss34 [mailto:notifications@github.com] 
Envoyé : lundi 9 décembre 2019 16:01
À : jesuisundesdeux/vigilo-webapp
Cc : 7castor; Author
Objet : Re: [jesuisundesdeux/vigilo-webapp] bug appli vigilo android (#47)

 

Bonjour,

Quelle est la version de l'application sur Android ?
L'application est elle installée sur la carte SD ?
Quel est le bug en question, (message d'erreur ? si oui lequel ?)

Cordialement

**Comment by kentiss34** [comment]
8.0.0 n'est pas la version de l'application mais la version Android.

La version de l'application est disponible via le bouton "A propos"
Avez vous essayé d’effacer le cache de l'appli / désinstaller/réinstaller ?

**Comment by 7castor** [comment]
La version de l'application 0.0.12

Avez vous essayé d’effacer le cache de l'appli / désinstaller/réinstaller ? Oui, même problème

 

De : kentiss34 [mailto:notifications@github.com] 
Envoyé : lundi 9 décembre 2019 16:59
À : jesuisundesdeux/vigilo-webapp
Cc : 7castor; Author
Objet : Re: [jesuisundesdeux/vigilo-webapp] bug appli vigilo android (#47)

 

8.0.0 n'est pas la version de l'application mais la version Android.

La version de l'application est disponible via le bouton "A propos"
Avez vous essayé d’effacer le cache de l'appli / désinstaller/réinstaller ?

**Comment by kentiss34** [comment]
Quelle est la release indiquée ? (Release XXX) ?
Avez vous essayé avec une photo qui n'est pas sur la carte SD ?

**Comment by 7castor** [comment]
Quelle est la release indiquée ? (Release XXX) ? v2.1 (release 150)
Avez vous essayé avec une photo qui n'est pas sur la carte SD ? oui    même erreur copy du fichier dans file// mnt/sdcart/vigilo/tmp_picture.jpg



 

De : kentiss34 [mailto:notifications@github.com] 
Envoyé : lundi 9 décembre 2019 17:27
À : jesuisundesdeux/vigilo-webapp
Cc : 7castor; Author
Objet : Re: [jesuisundesdeux/vigilo-webapp] bug appli vigilo android (#47)

**Comment by kentiss34** [comment]
Pouvez vous essayer de sauvegarder vos observations et retester ?
Cette fonctionnalité permet aussi de forcer les droits en ecriture

Cordialement,

**Comment by 7castor** [comment]
J’ai sauvegardé mais je n’ai aucune observation du fait du bug. Même pb

Cordialement

 

De : kentiss34 [mailto:notifications@github.com] 
Envoyé : lundi 9 décembre 2019 17:54
À : jesuisundesdeux/vigilo-webapp
Cc : 7castor; Author
Objet : Re: [jesuisundesdeux/vigilo-webapp] bug appli vigilo android (#47)

 

Pouvez vous essayer de sauvegarder vos observations et retester ?
Cette fonctionnalité permet aussi de forcer les droits en ecriture

Cordialement,

**Comment by kentiss34** [comment]
Le problème est très difficile à diagnostiquer.
Essayons encore quelques trucs.

Les données ont elles été effacées ? il  y a un bouton dans le paramètre
des applis du téléphone pour ca
Pouvez essayer de déplacer l'appli sur la carte SD puis la redeplacer sur
la memoire interne ?
Dans la configuration de l'appli sur les paramètres du téléphone,
l'application a t'elle bien les droits d'accès aux fichiers ?

Cordialement

**Comment by kentiss34** [comment]
Pour info j'ai ajouté un autorisation supplémentaire pour la prochaine version. J'espère que ça corrigera le problème.

**Comment by 7castor** [comment]
Merci,

J’ai coché les autorisations, toujours le même pb. Je ne vois pas comment transférer l’appli sur la carte SD.

Si vous pouviez laisser les messages d’erreur apparents plus longtemps, on pourrait faire des copies d’écran.

Cordialement.

 

De : kentiss34 [mailto:notifications@github.com] 
Envoyé : mercredi 11 décembre 2019 16:34
À : jesuisundesdeux/vigilo-webapp
Cc : 7castor; Author
Objet : Re: [jesuisundesdeux/vigilo-webapp] bug appli vigilo android (#47)

 

Pour info j'ai ajouté un autorisation supplémentaire pour la prochaine version. J'espère que ça corrigera le problème.

**Comment by kentiss34** [comment]
Vous pouvez également filmer l'écran pendant l'erreur.
Le déplacement de l'application vers la carte SD se fait via les paramètres
du téléphone / applications / vigilo.

Cordialement
