### ISSUE TITLE
Message d'erreur : La localisation doit se trouver dans la zone géographique choisie.

### ISSUE THREAD

**Issue by trachyboy** [jesuisundesdeux/vigilo-webapp#48]
## Bug

J'uploade une photo comportant des données de géolocalisation ainsi que l'heure afin d'accélérer et fiabiliser mes signalements

Elle est issue d'une GoPro Hero 7 en mode timelapse.
Le GPS est activé.
La même photo est correctement positionnée sur la carte par Mapillary.

Voici la photo : ![G0010571](https://user-images.githubusercontent.com/60044242/72668779-91f4d300-3a2a-11ea-8bfa-dc0a0a5651a9.JPG)

Elle se situe rue de la Haluchère

## Navigateur
Mozilla Firefox pour Ubuntu 72.0.1 (64 bits)

## Zone géographique

Nantes

## Version
Nantes Métropole (0.0.12)

**Comment by tcoupin** [comment]
Coordonnées dans les Exif : 47° 14' 35,112" N 1° 30' 42,792" O
En décimal  : 47,243086666666667  -1,511886666666667

Config serveur de Nantes :
```
    "coordinate_lat_min": "47.124812",
    "coordinate_lat_max": "47.332308",
    "coordinate_lon_min": "-1.847763",
    "coordinate_lon_max": "-1.188583",
```

Effectivement, ça devrait passer...

**Comment by dobriseb** [comment]
Même problème sur La Rochelle depuis la nouvelle version.

**Comment by tcoupin** [comment]
Uniquement les longitudes négatives ;)
Bug dans la librairie de lecture des exif : https://github.com/hMatoba/piexifjs/commit/94d37e9edfddcc074d59a2283533b8b05be8e486

**Comment by dobriseb** [comment]
Merci @tcoupin
