### ISSUE TITLE
[Suggestion] Nouvelle catégorie de signalement: "Travaux - Rupture de continuité cyclable"

### ISSUE THREAD

**Issue by Ekareya** [jesuisundesdeux/vigilo-webapp#58]

**Comment by tcoupin** [comment]
Ping @kentiss34 @badele

**Comment by kentiss34** [comment]
Cette catégorie est trop vague et peut rentrer conflit avec les catégories existantes liées à la signalisation / au vehicule ou object génants, au défaut d'entretien ou encore à un aménagement mal conçut.
Les travaux sont à prendre comme une cause, les catégories visent à lister les conséquences.

**Comment by Ekareya** [comment]
Je vois,la suggestion j'ai eu un signalement à faire sur Clermont-Ferrand, ou justement aucune de ses catégories ne me parait convenir. il y a des travaux au niveau de l'autoroute, et ils ont complétement coupé la piste cyclable qui passait par au dessus et qui relie deux villes, et du coup, ce n'est ni un défaut de signalisation parce dans les fait la piste cyclable n'existe plus, ni un objet gênant ( ou alors on considère l'autoroute comme un objet gênant XD ce dont je ne suis pas contre mais bon c'est un autre débat) et c'est pour moi, pas non plus un aménagement mal conçut. il n'y a pas la notion de temporaire la dedans, et que pour avoir un aménagement mal concus, il faudrait justement qu'il y ai un aménagement, et cette situation est malheureusement un grand classique des travaux sur la région clermontoise.

**Comment by Ekareya** [comment]
j'ai finis par mettre absence d'aménagement ( A67AF082 ). en fait c'est un petit peu de tout en même temps, c'est une absence d'aménagement temporaire, mais c'est aussi un aménagement temporaire mal conçu ( car n’intégrant ni les piétons ni les cycles) et c'est quelque chose que l'on essaye de mettre en lumière au niveau des services techniques, d'ou le ressenti d'un besoin d'une catégorie distincte

**Comment by kentiss34** [comment]
Hello effectivement c'est la bonne catégorie a utiliser pour le moment.
Un système de tags est en chantier afin de permettre de classifier plus précisément les observations.
