### ISSUE TITLE
Specs Résolutions

### ISSUE THREAD

**Issue by qhess34** [jesuisundesdeux/vigilo-webapp#61]
Depuis la version 0.0.14 du backend il est possible de poster des résolutions.

Le principe est assez similaire à l'ajout d'observations : 

1/ On créer une resolution comme une observation avec /create_resolution.php en precisant une liste de token liée à celle-ci (https://github.com/jesuisundesdeux/vigilo-backend/blob/master/doc/REST_API.md#cr%C3%A9er-r%C3%A9solution).
2/ On ajoute l'image avec  /add_image.php?type=resolution&token=XXX ou le token est le token de la résolution

Est-il possible de rajouter cette fonctionnalité à la web-app ? 
A dispo si besoin de plus de précisions.

**Comment by tcoupin** [comment]
sur l'appli android tu te bases sur quels critères pour proposer des observations ? A minima une obs non résolu et sinon critère géo uniquement ?

**Comment by qhess34** [comment]
Hello,

Je récupère les observations similaires directement avec l'URL :
/get_issues.php?scope=SCOPE&lat=LATITUDE&lon=LONGITUDE&radius=100 où
Longitude et latitude sont les coordonnées pointées sur la carte de la
résolution.

Quentin

**Comment by tcoupin** [comment]
Salut @qhess34 

j'ai pousser sur la branche develop la feature.
J'ai pu résoudre https://app.vigilo.city/develop?token=HFIDVTWW&instance=kentiss34%20(uat) et https://app.vigilo.city/develop?token=50A143DD&instance=kentiss34%20(uat)

Pour ajouter une résolution, c'est comme si on ajouter une observation, sauf qu'il faut sélectionner "Un problème a été corrigé !" dans la catégorie.

Tu peux regarder, me faire un retour sur la feature et sur https://github.com/jesuisundesdeux/vigilo-backend/issues/228

**Comment by tcoupin** [comment]
et la fonction n'est active que pour les backend >=0.0.14
