### ISSUE TITLE
erreur javascript .toLowerCase of undefined sur fermeture du drawer des filtres

### ISSUE THREAD

**Issue by abenhamdine** [jesuisundesdeux/vigilo-webapp#63]
## Bug

le bug se produit quand on clique sur le bouton pour valider les filtres sélectionnés ou quand on clique en dehors du drawer  

![image](https://user-images.githubusercontent.com/7466144/94008761-d0097a00-fda3-11ea-8fe2-42773a90f387.png)

![image](https://user-images.githubusercontent.com/7466144/94008846-efa0a280-fda3-11ea-95a4-a46d9133fa86.png)

![image](https://user-images.githubusercontent.com/7466144/94008615-95074680-fda3-11ea-8ad9-9976ba2208e2.png)

apparemment le coupable est là : 

![image](https://user-images.githubusercontent.com/7466144/94009760-304ceb80-fda5-11ea-8566-9f27b438a801.png)

## Navigateur

Chrome 85.0.4183.102
Mac Os X catalina

## Zone géographique

Montpellier

## Version

1.7.3

**Comment by abenhamdine** [comment]
je veux bien faire la PR si on me guide un peu, notamment sur ce qu'est censé faire getData  

Je serai prêt à contribuer un peu (je suis adhérent de Vélocité Montpellier)

**Comment by tcoupin** [comment]
merci @abenhamdine . Pour le coup, c'est un problème de données.

@kentiss34 , peux-tu regarder pourquoi cette observation n'a pas de cityname ?
https://app.vigilo.city/?token=DE6F4306&instance=Montpellier


<img width="623" alt="image" src="https://user-images.githubusercontent.com/7457386/94060773-c5230980-fde4-11ea-9788-9987a7cc3f35.png">

**Comment by tcoupin** [comment]
Merci @kentiss34 pour le fix de la data.
