### ISSUE TITLE
Comment indiqué qu'une signalisation n'a plus lieu d'être car traitée

### ISSUE THREAD

**Issue by huiban** [jesuisundesdeux/vigilo-webapp#64]
Bonjour
On ne peut pas parler d'un bug mais je souhaiterais savoir comment signaler qu'une signalisation que j'ai déposée n'est plus d’actualité ?

Il s'agit de la sig  0C7B02D5

![20201007_112631](https://user-images.githubusercontent.com/44925609/95657092-e5580580-0b12-11eb-8345-793e7f5fe98f.jpg)

**Comment by tcoupin** [comment]
Cette fonction n'est pas encore développée sur la webapp.

**Comment by kentiss34** [comment]
Voir #61

**Comment by huiban** [comment]
Bonjour, pour information, la dernière version de l’application pour smartphone propose bien l’option Contribution / Ajouter une résolution.

Par contre la version Web de l’application n’offre pas cette option.

Cordialement

Jean-Jacques Huiban

De : kentiss34
Envoyé le :vendredi 6 novembre 2020 14:24
À : jesuisundesdeux/vigilo-webapp
Cc : huiban; Author
Objet :Re: [jesuisundesdeux/vigilo-webapp] Comment indiqué qu'une signalisation n'a plus lieu d'être car traitée (#64)

Voir #61

**Comment by kentiss34** [comment]
Bonjour Jean-Jacques,

Le fonctionnalité est prévue sur la webapp. Voir l'issue #61

**Comment by tcoupin** [comment]
C'est en place.
