### ISSUE TITLE
Oups... une erreur est survenue. 

### ISSUE THREAD

**Issue by aca44** [jesuisundesdeux/vigilo-webapp#69]
## Bug

Bonjour
sur l'interface public WEB en version admin, quand on choisi de trier les observations non modérées
![image](https://user-images.githubusercontent.com/75043621/100429474-ab789980-3095-11eb-8edf-28b0ab725894.png)
Merci de votre aide

## Navigateur

Navigateur FF sur ordinateur

## Zone géographique

https://app.vigilo.city/?token=BF13B1DE&instance=Nantes%20M%C3%A9tropole#!

## Version

version 1.7.4

**Comment by tcoupin** [comment]
OK, j'arrive à reproduire sur mon ordi. Je me penche dessus rapidement.

**Comment by aca44** [comment]
MErci pour le boulot et la réactivité
