### ISSUE TITLE
Soumettre impossible : error undefined

### ISSUE THREAD

**Issue by aca44** [jesuisundesdeux/vigilo-webapp#70]
## Bug
Bonjour 
Impossible de soumettre une observation en ligne
![image](https://user-images.githubusercontent.com/75043621/100615116-6b284e00-3317-11eb-9f40-d51dba34301a.png)

## Navigateur

FF sur Windows 10

## Zone géographique
Nantes metropole

## Version
1.8.0

**Comment by tcoupin** [comment]
fixed
