### ISSUE TITLE
TypeError: this is undefined 

### ISSUE THREAD

**Issue by aca44** [jesuisundesdeux/vigilo-webapp#71]
## Bug

Impossible de soumettre une observation en mode admin après modification par les modérateur 
![image](https://user-images.githubusercontent.com/75043621/100615542-04576480-3318-11eb-8b6d-a1e7640edbbf.png)

## Navigateur

FF sur Windows 10

## Zone géographique

Nantes métropole

## Version

1.8.0

**Comment by tcoupin** [comment]
fixed
