### ISSUE TITLE
cityname undefined quand get_issues vide

### ISSUE THREAD

**Issue by qhess34** [jesuisundesdeux/vigilo-webapp#77]
## Bug

L'erreur suivante est affichée si get_issues.php ne renvoie rien (exemple avec nantes => https://vigilo.placeauvelo-nantes.fr/get_issues.php?scope=44_nantesmetropole)

`TypeError: Cannot read property 'cityname' of undefined
`

Contenu de https://vigilo.placeauvelo-nantes.fr/get_issues.php?scope=44_nantesmetropole :

`[]`

## Navigateur

Chromium Version 73.0.3683.75 (Developer Build) built on Debian 9.8, running on Debian 9.13 (64-bit)

## Zone géographique

Quelle est la zone géographique utilisée ? 

Nantes

## Version

Indiquez ici a version de l'application, présente dans le menu en bas. 

0.0.16

**Comment by tcoupin** [comment]
Merci @edikabe pour la PR !
