### ISSUE TITLE
Error undefined quand je soumets un "Amenagement manquant"

### ISSUE THREAD

**Issue by RonanMeneu** [jesuisundesdeux/vigilo-webapp#85]
## Bug

Je tente de soumettre un Amenagement manquant a montpellier, pour le boulevard Philippe Lamour. Je renseigne tous les champs et mets une photo. Quand je soumets, j'ai une erreur "Ooops, undefined"
J'ai essaye au moins 4 fois.

## Navigateur

Chrome, sur laptop

## Zone géographique

Montpellier

## Version

1.10.0 et 0.0.16

**Comment by RonanMeneu** [comment]
Meme connecte a github, j'ai la meme erreur

**Comment by qhess34** [comment]
Salut,

Peux tu joindre la photo de ton observation à cette issue stp ?

Merci par avance

**Comment by RonanMeneu** [comment]
![image](https://user-images.githubusercontent.com/91117633/134135927-f10e941b-d752-4993-b172-caec9b3febaf.png)
Et voila

**Comment by RonanMeneu** [comment]
![image](https://user-images.githubusercontent.com/91117633/134136262-3bc8c073-7321-40f2-8ac0-ce056e37e7df.png)
Tous les champs, si ca peut aider

**Comment by qhess34** [comment]
Il me faudrait la photo que tu essayais de mettre sur vigilo (avec ses données exifs)

**Comment by RonanMeneu** [comment]
![blvdphilippelamour](https://user-images.githubusercontent.com/91117633/134136447-9bbf7c6b-97e1-4b80-ae44-0190a50bdfff.png)
La voici

**Comment by RonanMeneu** [comment]
non c'est un png. C'est ca le pb ?

**Comment by qhess34** [comment]
Oui, seuls les photos jpg sont acceptés.

**Comment by RonanMeneu** [comment]
Je viens de tenter avec jpg, meme erreur

**Comment by tcoupin** [comment]
Bonjour tous les 2,
la webapp supporte tous les formats (cf #24). Elle les convertit en jpeg avant transmission au serveur

**Comment by qhess34** [comment]
Effectivement l'image en png passe de mon coté. (Merci Thibault)

**Comment by qhess34** [comment]
Je viens de parvenir à reproduire le problème.
Il faut choisir sur la carte un point précis correspondant à l'obs en cliquant dessus, et pas uniquement saisir l'adresse.

**Comment by RonanMeneu** [comment]
ok je retente

**Comment by RonanMeneu** [comment]
Oui ca fonctionne. Merci. Ce serait bien que la fenetre mentionne qu'il faut faire un click et placer son point. Je n'avais pas vu ca.
Et que l'erreur soit "merci de placer le point sur la carte" plutot que undefined
A part ca, l'appli est vraiment cool.

**Comment by RonanMeneu** [comment]
Et merci pour votre reactivite !
