### ISSUE TITLE
disponibilité sur fdroid ?

### ISSUE THREAD

**Issue by vinber** [jesuisundesdeux/vigilo-webapp#89]
## Bug

L'application semble être libre. Elle est juste dispo sur le playstore de google, obligeant tous cyclistes vigilo à avoir un compte

## Navigateur

Android sans google

## Zone géographique

Bordeaux métro

## Version

Pas de version, juste le site

**Comment by qhess34** [comment]
Bonjour,

L'application est également dispo en ligne sur app.vigilo.city

Cordialement



Le sam. 16 oct. 2021 à 14:39, Vincent Bergeot ***@***.***> a
écrit :

**Comment by qhess34** [comment]
L'application Android étant developpé avec un Framework non compatible fdroid (Kodular) il n'est pas possible pour le moment de la portée dessus.
Cette solution pourra être envisageable quand on trouvera des développeurs Android.
